version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://server:8081
    networks:
      - auth-network


networks:
  auth-network:
    external: true