version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crud_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - auth-network

  server:
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - db              
    environment:
      - NODE_ENV=production
    networks:
      - auth-network
    restart: always  # Set restart policy to always

volumes:
  pgdata:
  
networks:
  auth-network:
    external: true
